### ISSUE TITLE
??

### ISSUE THREAD

**Issue by nk932714** [Inevio/WhatsappWeb#1]
Are you working on this ??

**Comment by jorge9200** [comment]
Hello @nk932714 !! Actually we only have our whatsappWeb marker, which opens a new browser window with whatsapp web in it. We have planed to have a more integrated whatsappWeb horbito app in the future, but we are not working right now on it.

But please stay tunned because we are going to liberate more integrated apps really soon. 

Thank you for your interest! and if you are interested on develop by yourself for us just email me at this address:

jfernandez@horbito.com

**Comment by nk932714** [comment]
thanks for your quick reply 👍
